### ISSUE TITLE
Alfred 开启了代理导致无法添加单词本，能否单独在插件里面关闭代理？

### ISSUE THREAD

**Issue by touchmii** [Rouwanzi/AlfredWorkflow_YoudaoTranslate#3]
[17:30:42.835] ERROR: YoudaoDict[Run Script] .
17:30:42 workflow.py:2055 DEBUG    ---------- YoudaoDict (1.21.0) ----------
17:30:42 workflow.py:1689 DEBUG    loading cached data: /Users/touchmii/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/Rouwanzi.workflow.YoudaoDict/translate_info.cpickle
17:30:42 workflow.py:1689 DEBUG    loading cached data: /Users/touchmii/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/Rouwanzi.workflow.YoudaoDict/translate_info.cpickle
17:30:42 workflow.py:2074 ERROR    Failed to parse: 127.0.0.1:1087127.0.0.1:1087
Traceback (most recent call last):
  File "/Users/touchmii/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.CEC60C68-8F39-4129-985F-43A20D0F8B7A/workflow/workflow.py", line 2067, in run
    func(self)
  File "functions.py", line 147, in main
    vb.add_word(query,translate_info[1],' '.join(translate_info[2]))
  File "functions.py", line 111, in add_word
    if self._add_word(word,soundmark,explains) or \
  File "functions.py", line 103, in _add_word
    self.res_of_addWord = self.conn.post(self.add_word_url,headers=self.header,data=data,allow_redirects=False)
  File "/Users/touchmii/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.CEC60C68-8F39-4129-985F-43A20D0F8B7A/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/touchmii/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.CEC60C68-8F39-4129-985F-43A20D0F8B7A/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/touchmii/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.CEC60C68-8F39-4129-985F-43A20D0F8B7A/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Users/touchmii/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.CEC60C68-8F39-4129-985F-43A20D0F8B7A/requests/adapters.py", line 410, in send
    conn = self.get_connection(request.url, proxies)
  File "/Users/touchmii/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.CEC60C68-8F39-4129-985F-43A20D0F8B7A/requests/adapters.py", line 304, in get_connection
    proxy_url = parse_url(proxy)
  File "/Users/touchmii/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.CEC60C68-8F39-4129-985F-43A20D0F8B7A/urllib3/util/url.py", line 199, in parse_url
    raise LocationParseError(url)
LocationParseError: Failed to parse: 127.0.0.1:1087127.0.0.1:1087

**Comment by TerryX-Lee** [comment]
最近比较忙，我回头看一下

**Comment by TerryX-Lee** [comment]
你这个代理写的有问题？ 为什么拿到的url `LocationParseError: Failed to parse: 127.0.0.1:1087127.0.0.1:1087`是这样的
